[package]
name = "aider_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
handlebars = "4.2.1"
serde = { version = "1.0", features = ["derive"] }
actix-web = "3.3.2"
regex = "1.4.5"
